import { useMutation } from "@tanstack/react-query";
import { relatoriosApi } from "@/api/relatoriosApi";
export const useRelatorioFolhaAnalitica = () => useMutation({ mutationFn: relatoriosApi.folhaAnalitica });
export const useRelatorioFolhaSintetica = () => useMutation({ mutationFn: relatoriosApi.folhaSintetica });
export const useRelatorioINSS = () => useMutation({ mutationFn: relatoriosApi.resumoINSS });
export const useRelatorioIRRF = () => useMutation({ mutationFn: relatoriosApi.resumoIRRF });
export const useRelatorioFGTS = () => useMutation({ mutationFn: relatoriosApi.resumoFGTS });
export const useRelatorioGRF = () => useMutation({ mutationFn: relatoriosApi.grf });
export const useRelatorioFichaRegistro = () => useMutation({ mutationFn: relatoriosApi.fichaRegistro });
export const useRelatorio13 = () => useMutation({ mutationFn: relatoriosApi.decimoTerceiro });
