import React, { useState } from "react";
import { Wizard } from "./Wizard";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Calculator } from "lucide-react";
interface CalculoFolhaWizardProps { competencia: string; colaboradores: { id: string; nome: string }[]; onComplete: (data: any) => void; onCancel?: () => void; }
export function CalculoFolhaWizard({ competencia, colaboradores, onComplete, onCancel }: CalculoFolhaWizardProps) {
  const [data, setData] = useState({ tipoCalculo: "TODOS", colaboradoresSelecionados: [] as string[], opcoes: { recalcular: false, incluirAdiantamento: false, fecharFolha: false } });
  const toggleColaborador = (id: string) => setData(prev => ({ ...prev, colaboradoresSelecionados: prev.colaboradoresSelecionados.includes(id) ? prev.colaboradoresSelecionados.filter(c => c !== id) : [...prev.colaboradoresSelecionados, id] }));
  const steps = [{ title: "Tipo de Cálculo", component: <div className="space-y-4"><div className="p-4 bg-blue-50 rounded-lg flex gap-3"><Calculator className="h-5 w-5 text-blue-600" /><div><p className="font-medium">Competência: {competencia}</p><p className="text-sm text-muted-foreground">{colaboradores.length} colaboradores ativos</p></div></div><div><Label>Calcular para</Label><Select value={data.tipoCalculo} onValueChange={v => setData(prev => ({ ...prev, tipoCalculo: v }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="TODOS">Todos os Colaboradores</SelectItem><SelectItem value="SELECIONADOS">Colaboradores Selecionados</SelectItem></SelectContent></Select></div></div>, isValid: true },
  { title: "Seleção", component: data.tipoCalculo === "TODOS" ? <div className="p-4 bg-green-50 rounded-lg"><p className="font-medium">Todos os {colaboradores.length} colaboradores serão calculados.</p></div> : <div className="space-y-2 max-h-64 overflow-y-auto">{colaboradores.map(c => <div key={c.id} className="flex items-center gap-2 p-2 hover:bg-muted rounded"><Checkbox checked={data.colaboradoresSelecionados.includes(c.id)} onCheckedChange={() => toggleColaborador(c.id)} /><span>{c.nome}</span></div>)}</div>, isValid: data.tipoCalculo === "TODOS" || data.colaboradoresSelecionados.length > 0 },
  { title: "Opções", component: <div className="space-y-4">{[{ key: "recalcular", label: "Recalcular já processados" }, { key: "incluirAdiantamento", label: "Incluir adiantamento salarial" }, { key: "fecharFolha", label: "Fechar folha após cálculo" }].map(opt => <div key={opt.key} className="flex items-center gap-2"><Checkbox checked={(data.opcoes as any)[opt.key]} onCheckedChange={v => setData(prev => ({ ...prev, opcoes: { ...prev.opcoes, [opt.key]: v } }))} /><Label>{opt.label}</Label></div>)}</div>, isValid: true },
  { title: "Confirmação", component: <div className="space-y-2 bg-muted p-4 rounded-lg"><p><strong>Competência:</strong> {competencia}</p><p><strong>Colaboradores:</strong> {data.tipoCalculo === "TODOS" ? "Todos" : data.colaboradoresSelecionados.length}</p><p><strong>Recalcular:</strong> {data.opcoes.recalcular ? "Sim" : "Não"}</p><p><strong>Fechar após:</strong> {data.opcoes.fecharFolha ? "Sim" : "Não"}</p></div>, isValid: true }];
  return <Wizard steps={steps} onComplete={() => onComplete({ competencia, ...data })} onCancel={onCancel} title="Calcular Folha de Pagamento" />;
}
export default CalculoFolhaWizard;
