// V14-057: categoriasTrabalhador.ts
export const categoriasTrabalhador = [
  { codigo: "101", descricao: "Empregado - Geral" },
  { codigo: "102", descricao: "Empregado - Trabalhador Rural por Pequeno Prazo" },
  { codigo: "103", descricao: "Empregado - Aprendiz" },
  { codigo: "104", descricao: "Empregado - Doméstico" },
  { codigo: "105", descricao: "Empregado - Contrato a Termo Firmado" },
  { codigo: "106", descricao: "Trabalhador Temporário" },
  { codigo: "107", descricao: "Empregado - Contrato de Trabalho Intermitente" },
  { codigo: "201", descricao: "Trabalhador Avulso Portuário" },
  { codigo: "202", descricao: "Trabalhador Avulso Não Portuário" },
  { codigo: "301", descricao: "Servidor Público - Titular de Cargo Efetivo" },
  { codigo: "302", descricao: "Servidor Público - Ocupante de Cargo Exclusivo em Comissão" },
  { codigo: "303", descricao: "Agente Político" },
  { codigo: "305", descricao: "Servidor Público - Indicado para Conselho ou Órgão Representativo" },
  { codigo: "306", descricao: "Servidor Público - Contratado por Tempo Determinado" },
  { codigo: "309", descricao: "Agente Público - Outros" },
  { codigo: "401", descricao: "Dirigente Sindical" },
  { codigo: "410", descricao: "Trabalhador Cedido" },
  { codigo: "701", descricao: "Contribuinte Individual - Autônomo" },
  { codigo: "711", descricao: "Contribuinte Individual - Transportador Autônomo" },
  { codigo: "712", descricao: "Contribuinte Individual - Transportador de Passageiros" },
  { codigo: "721", descricao: "Contribuinte Individual - Diretor não Empregado" },
  { codigo: "722", descricao: "Contribuinte Individual - Empresário" },
  { codigo: "723", descricao: "Contribuinte Individual - Sócio" },
  { codigo: "731", descricao: "Contribuinte Individual - Cooperado" },
  { codigo: "734", descricao: "Contribuinte Individual - Transportador Cooperado" },
  { codigo: "738", descricao: "Contribuinte Individual - Cooperado Filiado a Cooperativa de Produção" },
  { codigo: "741", descricao: "Contribuinte Individual - Microempreendedor Individual" },
  { codigo: "751", descricao: "Contribuinte Individual - Magistrado Classista Temporário" },
  { codigo: "761", descricao: "Contribuinte Individual - Associado Eleito para Direção de Cooperativa" },
  { codigo: "771", descricao: "Contribuinte Individual - Membro de Conselho Tutelar" },
  { codigo: "781", descricao: "Ministro de Confissão Religiosa ou Membro de Vida Consagrada" },
  { codigo: "901", descricao: "Estagiário" },
  { codigo: "902", descricao: "Médico Residente" },
  { codigo: "903", descricao: "Bolsista" },
  { codigo: "904", descricao: "Participante de Curso de Formação" },
  { codigo: "905", descricao: "Atleta Não Profissional em Formação" },
];

export type CategoriaTrabalhador = typeof categoriasTrabalhador[number];

