import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { PageHeader } from "@/components/ui/page-header";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Save, Lock, Shield, Key } from "lucide-react";
export function SegurancaConfigPage() {
  return (<div className="space-y-6"><PageHeader title="Segurança" description="Configurações de segurança e acesso"><Button><Save className="h-4 w-4 mr-2" />Salvar</Button></PageHeader><div className="grid gap-6"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Lock className="h-5 w-5" />Política de Senhas</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label>Tamanho mínimo</Label><Select defaultValue="8"><SelectTrigger className="w-32"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="6">6 caracteres</SelectItem><SelectItem value="8">8 caracteres</SelectItem><SelectItem value="10">10 caracteres</SelectItem><SelectItem value="12">12 caracteres</SelectItem></SelectContent></Select></div><div className="flex items-center justify-between"><div><Label>Exigir caracteres especiais</Label></div><Switch defaultChecked /></div><div className="flex items-center justify-between"><div><Label>Exigir números</Label></div><Switch defaultChecked /></div><div><Label>Expiração de senha (dias)</Label><Select defaultValue="90"><SelectTrigger className="w-32"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="30">30 dias</SelectItem><SelectItem value="60">60 dias</SelectItem><SelectItem value="90">90 dias</SelectItem><SelectItem value="never">Nunca</SelectItem></SelectContent></Select></div></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Shield className="h-5 w-5" />Autenticação</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex items-center justify-between"><div><Label>Autenticação em 2 fatores</Label><p className="text-sm text-muted-foreground">Obrigatório para administradores</p></div><Switch defaultChecked /></div><div className="flex items-center justify-between"><div><Label>Bloquear após tentativas</Label><p className="text-sm text-muted-foreground">Bloquear conta após 5 tentativas</p></div><Switch defaultChecked /></div></CardContent></Card></div></div>);
}
export default SegurancaConfigPage;
