// This file is auto-generated by Lovable.
// Since you've moved to an external DB, this file is kept for backward compatibility
// but authentication should now be handled via your project's auth provider.

import { supabase } from "../supabase/client";

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: any) => {
      return supabase.auth.signInWithOAuth({
        provider,
        options: {
          redirectTo: opts?.redirect_uri || window.location.origin
        }
      });
    },
  },
};
