import type { Meta, StoryObj } from "@storybook/react";
import { AlertBanner } from "./AlertBanner";
const meta: Meta<typeof AlertBanner> = { title: "Notifications/AlertBanner", component: AlertBanner };
export default meta;
type Story = StoryObj<typeof AlertBanner>;
export const Success: Story = { args: { type: "success", title: "Operação realizada", description: "Os dados foram salvos." } };
export const Error: Story = { args: { type: "error", title: "Erro", description: "Algo deu errado." } };
export const Warning: Story = { args: { type: "warning", title: "Atenção", description: "Verifique os dados." } };
export const Info: Story = { args: { type: "info", title: "Informação", description: "Nova versão disponível." } };
export const Dismissible: Story = { args: { type: "info", title: "Aviso", dismissible: true } };
