-- V16-002: Colaboradores Schema

CREATE TABLE IF NOT EXISTS colaboradores (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  empresa_id UUID NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  matricula VARCHAR(20),
  nome VARCHAR(255) NOT NULL,
  nome_social VARCHAR(255),
  cpf CHAR(11) UNIQUE NOT NULL,
  rg VARCHAR(20),
  rg_orgao VARCHAR(20),
  rg_uf CHAR(2),
  rg_data DATE,
  pis CHAR(11),
  ctps_numero VARCHAR(20),
  ctps_serie VARCHAR(10),
  ctps_uf CHAR(2),
  titulo_eleitor VARCHAR(20),
  zona_eleitoral VARCHAR(10),
  secao_eleitoral VARCHAR(10),
  cnh VARCHAR(20),
  cnh_categoria VARCHAR(5),
  cnh_validade DATE,
  reservista VARCHAR(20),
  data_nascimento DATE NOT NULL,
  sexo CHAR(1),
  estado_civil VARCHAR(20),
  nacionalidade VARCHAR(50) DEFAULT 'Brasileiro',
  naturalidade VARCHAR(100),
  nome_mae VARCHAR(255),
  nome_pai VARCHAR(255),
  raca_cor VARCHAR(20),
  deficiencia BOOLEAN DEFAULT false,
  tipo_deficiencia VARCHAR(50),
  email VARCHAR(255),
  email_pessoal VARCHAR(255),
  telefone VARCHAR(20),
  celular VARCHAR(20),
  cep CHAR(8),
  logradouro VARCHAR(255),
  numero VARCHAR(10),
  complemento VARCHAR(100),
  bairro VARCHAR(100),
  cidade VARCHAR(100),
  uf CHAR(2),
  escolaridade VARCHAR(50),
  formacao VARCHAR(100),
  data_admissao DATE NOT NULL,
  data_demissao DATE,
  tipo_admissao VARCHAR(50),
  tipo_contrato VARCHAR(20) NOT NULL DEFAULT 'indeterminado',
  cargo_id UUID REFERENCES cargos(id),
  departamento_id UUID REFERENCES departamentos(id),
  sindicato_id UUID REFERENCES sindicatos(id),
  gestor_id UUID REFERENCES colaboradores(id),
  salario DECIMAL(12,2) NOT NULL,
  tipo_salario VARCHAR(20) DEFAULT 'mensal',
  jornada_semanal INTEGER DEFAULT 44,
  horario_entrada TIME,
  horario_saida TIME,
  horario_intervalo INTEGER DEFAULT 60,
  banco VARCHAR(50),
  agencia VARCHAR(10),
  agencia_dv CHAR(1),
  conta VARCHAR(20),
  conta_dv CHAR(1),
  tipo_conta VARCHAR(20) DEFAULT 'corrente',
  pix_tipo VARCHAR(20),
  pix_chave VARCHAR(100),
  foto_url TEXT,
  status VARCHAR(20) DEFAULT 'ativo',
  primeiro_emprego BOOLEAN DEFAULT false,
  optante_fgts BOOLEAN DEFAULT true,
  categoria_trabalhador VARCHAR(10) DEFAULT '101',
  vinculo_trabalhista VARCHAR(10) DEFAULT '10',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID,
  updated_by UUID
);

-- DEPENDENTES
CREATE TABLE IF NOT EXISTS dependentes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  colaborador_id UUID NOT NULL REFERENCES colaboradores(id) ON DELETE CASCADE,
  empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE,
  nome VARCHAR(255),
  cpf CHAR(11),
  data_nascimento DATE,
  parentesco VARCHAR(50),
  sexo CHAR(1),
  ir_dependente BOOLEAN DEFAULT false,
  sf_dependente BOOLEAN DEFAULT false,
  deficiencia BOOLEAN DEFAULT false,
  certidao_tipo VARCHAR(20),
  certidao_numero VARCHAR(50),
  certidao_cartorio VARCHAR(100),
  descricao TEXT,
  valor DECIMAL(15,2) DEFAULT 0,
  data_inicio DATE,
  data_fim DATE,
  ativo BOOLEAN DEFAULT true,
  status VARCHAR(50) DEFAULT 'ativo',
  observacoes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID,
  updated_by UUID
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_colaboradores_empresa ON colaboradores(empresa_id);
CREATE INDEX IF NOT EXISTS idx_colaboradores_cpf ON colaboradores(cpf);
CREATE INDEX IF NOT EXISTS idx_colaboradores_status ON colaboradores(status);
CREATE INDEX IF NOT EXISTS idx_colaboradores_cargo ON colaboradores(cargo_id);
CREATE INDEX IF NOT EXISTS idx_colaboradores_depto ON colaboradores(departamento_id);
CREATE INDEX IF NOT EXISTS idx_dependentes_colab ON dependentes(colaborador_id);
