REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_admin(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_roles(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_default_empresa(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_empresas(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.user_belongs_to_empresa(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.anonimizar_dados_pessoais(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_link_gov_br_account(uuid, text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.processar_ajuste_aprovado(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_colaborador_banco_horas(uuid) FROM anon;