// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { toast } from 'sonner';
import type { Database } from './types';
import { secureJsonParse } from '@/utils/secureJson';
import { loggerService } from '@/services/loggerService';


// Projeto ativo: variáveis de ambiente são obrigatórias (P0-008).
// Sem fallback hardcoded — qualquer ausência falha o build com mensagem clara.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// Em dev local, VITE_SUPABASE_FUNCTIONS_BASE=/functions/v1 faz a bridge passar
// pelo proxy do Vite (que remove o header Origin, permitido pelo gate estrito
// da edge function). Em produção, fica vazio → URL absoluta do Supabase.
const FUNCTIONS_BASE = import.meta.env.VITE_SUPABASE_FUNCTIONS_BASE?.trim() || `${SUPABASE_URL}/functions/v1`;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    '[SUPABASE] VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY (ou VITE_SUPABASE_ANON_KEY) ' +
      'são obrigatórias. Configure no .env antes do build. Veja .env.example.',
  );
}

// Base client usado para Auth/Storage. Toda I/O de dados vai pela bridge.
// Exportado também como `supabaseBase` para uso em casos especiais (ex.: client.base.ts)
// onde o proxy de bridge não deve mediar (audit_log, tabelas de sistema, etc).
export const supabaseBase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    }
  }
);

// ── Idempotency retry helper (P3-061) ───────────────────────────────────────
// Backoff: 1s → 5s → 25s. Máximo 3 tentativas.
// Não retry: 4xx exceto 429; não retry se idempotency-key inválida (409).
// Para writes: auto-injeta Idempotency-Key gerado pelo cliente (crypto.randomUUID).
// Para reads: sem retry (reads são idempotent por natureza).

const RETRY_DELAYS_MS = [1_000, 5_000, 25_000];
const RETRYABLE_STATUS_CODES = new Set([429, 502, 503, 504]);

async function sleep(ms: number): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

function isRetryableHttpError(res: Response): boolean {
  return RETRYABLE_STATUS_CODES.has(res.status);
}

async function fetchWithRetry(
  url: string,
  options: RequestInit,
  isWrite: boolean,
): Promise<{ res: Response; idempotencyKey: string | null }> {
  let idempotencyKey: string | null = null;

  for (let attempt = 0; attempt <= RETRY_DELAYS_MS.length; attempt++) {
    const headers = { ...options.headers } as Record<string, string>;

    // Writes GET idempotency key auto-gerado (não afeta reads).
    if (isWrite && !headers['Idempotency-Key']) {
      idempotencyKey = crypto.randomUUID();
      headers['Idempotency-Key'] = idempotencyKey;
    }

    const res = await fetch(url, { ...options, headers });

    // Sucesso: retorna imediatamente.
    if (res.ok) return { res, idempotencyKey };

    // Não-retryable: 4xx exceto 429 → fail fast.
    if (res.status >= 400 && res.status < 500 && res.status !== 429) {
      return { res, idempotencyKey };
    }

    // Último retry agotado: retorna erro final.
    if (attempt === RETRY_DELAYS_MS.length) return { res, idempotencyKey };

    // Retryable: aplica backoff e tenta novamente.
    const delay = RETRY_DELAYS_MS[attempt];
    await sleep(delay);
  }

  // Fallback impossível mas requerido pelo TS.
  return { res: new Response(null, { status: 500 }), idempotencyKey };
}

// --- external-db-bridge Proxy ---
// Contrato real (descoberto via probe):
//   { action: 'select'|'insert'|'update'|'delete'|'rpc',
//     table: string,
//     columns?: string,
//     data?: object | object[],
//     filters?: Array<{ column: string; op: string; value: unknown }>,
//     order?: { column: string; ascending?: boolean },
//     limit?: number,
//     single?: boolean }

type Action = 'select' | 'insert' | 'update' | 'delete' | 'rpc' | 'upsert';

interface Filter {
  column: string;
  op: string;
  value: unknown;
  extraOp?: string;
}

interface BridgePayload {
  columns?: string;
  data?: Record<string, unknown> | Record<string, unknown>[];
  filters?: Filter[];
  order?: { column: string; ascending?: boolean };
  limit?: number;
  offset?: number;
  single?: boolean;
  countMode?: string;
  params?: Record<string, unknown>;
}

interface BridgeResponse<T = any> {
  data: T | null;
  count?: number;
  error: { message: string } | null;
}

interface RpcBody {
  action: Action;
  table?: string;
  fn?: string;
  columns?: string;
  data?: Record<string, unknown> | Record<string, unknown>[];
  filters?: Filter[];
  order?: { column: string; ascending?: boolean };
  limit?: number;
  offset?: number;
  single?: boolean;
  countMode?: string;
  params?: Record<string, unknown>;
}

const callBridge = async <T = any>(
  action: Action,
  target: string,
  payload: BridgePayload = {}
): Promise<BridgeResponse<T>> => {
  const { data: { session } } = await supabaseBase.auth.getSession();
  const body: RpcBody = {
    action,
    ...(action === 'rpc' ? { fn: target } : { table: target }),
    ...payload,
  };

  // P0-009: nunca usar anon key como Authorization. Writes exigem JWT válido;
  // reads anônimos continuam permitidos (compatibilidade com o frontend).
  const bearerToken = session?.access_token;
  const isWrite = action === 'insert' || action === 'update' || action === 'delete' || action === 'upsert';
  if (isWrite && !bearerToken) {
    return { data: null, count: 0, error: { message: 'Sessão inválida — faça login novamente.' } };
  }

  try {
    // P3-061: retry com backoff para writes; idempotency key auto-injetada.
    const { res, idempotencyKey } = await fetchWithRetry(
      `${FUNCTIONS_BASE}/external-db-bridge`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'apikey': SUPABASE_PUBLISHABLE_KEY,
          'Authorization': `Bearer ${bearerToken || SUPABASE_PUBLISHABLE_KEY}`,
        },
        body: JSON.stringify(body),
      },
      isWrite,
    );
    const rawText = await res.text().catch(() => '{}');
    const json: {
      data?: unknown;
      count?: number;
      error?: string;
      duration_ms?: number;
    } = secureJsonParse(rawText);

    // 409 = idempotency key reutilizada com payload diferente → não retryable aqui
    // (o cliente que gerou a key deve evitar reuse). Fail fast.
    if (!res.ok || json.error) {
      const errorMsg = json.error || `Erro HTTP ${res.status}`;
      loggerService.error('BRIDGE_SCHEMA_ERROR', { action, target, errorMsg });

      // Erros de função/tabela/coluna ausente NÃO devem poluir a UI com toast.
      // Apenas propagamos o erro para quem chamou tratar (ou ignorar).
      const isMissingObject = /Could not find the (function|table)|schema cache|does not exist|column .* does not exist/i.test(errorMsg);
      if (!isMissingObject) {
        toast.error('Erro ao processar operação no banco de dados.', {
          duration: 6000,
        });
      }

      return { data: null, count: 0, error: { message: errorMsg } };
    }
    let data: unknown = json.data;
    if (payload.single) data = Array.isArray(data) ? ((data as unknown[])[0] ?? null) : data;

    if (json.duration_ms && json.duration_ms > 1000) {
      loggerService.warn(`[BRIDGE_SLOW_QUERY] ${action} em ${target} demorou ${json.duration_ms}ms`, { action, target, duration_ms: json.duration_ms });
    }

    return { data: data as T | null, count: json.count, error: null };
  } catch (err: unknown) {
    const isNetworkError =
      err instanceof Error &&
      (err.message === 'Failed to fetch' || err.name === 'TypeError');
    const errorMsg = isNetworkError
      ? 'Erro de conexão com o banco. Verifique sua internet.'
      : (err instanceof Error ? err.message : 'Erro desconhecido');

    loggerService.error('BRIDGE_FATAL_ERROR', { isNetworkError }, err instanceof Error ? err : undefined);

    if (isNetworkError) {
      toast.error(errorMsg, { duration: 5000 });
    }

    return { data: null, error: { message: errorMsg } };
  }
};

type AnyFn = (...args: unknown[]) => unknown;

// Resultado resolved de qualquer cadeia da bridge.
type BridgeResult = { data: any; error: { message: string } | null; count?: number };

// ── Chainable query builder types (P2-043) ─────────────────────────────────
// Substitui o antigo QueryBuilder plano. Permite encadear .eq/.select/.single()
// sem `as any` e sem warnings do compilador.
//
// P2-043: CENTENA de `as any` nos services era causada por QueryBuilder retornando
// QueryBuilder em todos os métodos — TypeScript não distinguia early vs terminal
// stages da cadeia. Com tipos chainable, cada método retorna o tipo correto.
interface TerminalQueryBuilder {
  select: (columns?: string, options?: { count?: string }) => TerminalQueryBuilder;
  insert: (data: Record<string, unknown> | Record<string, unknown>[]) => TerminalQueryBuilder;
  update: (data: Record<string, unknown>) => TerminalQueryBuilder;
  delete: () => TerminalQueryBuilder;
  upsert: (data: Record<string, unknown> | Record<string, unknown>[]) => TerminalQueryBuilder;
  eq: (column: string, value: unknown) => TerminalQueryBuilder;
  neq: (column: string, value: unknown) => TerminalQueryBuilder;
  gt: (column: string, value: unknown) => TerminalQueryBuilder;
  gte: (column: string, value: unknown) => TerminalQueryBuilder;
  lt: (column: string, value: unknown) => TerminalQueryBuilder;
  lte: (column: string, value: unknown) => TerminalQueryBuilder;
  like: (column: string, value: unknown) => TerminalQueryBuilder;
  ilike: (column: string, value: unknown) => TerminalQueryBuilder;
  in: (column: string, value: unknown[]) => TerminalQueryBuilder;
  is: (column: string, value: unknown) => TerminalQueryBuilder;
  not: (column: string, op: string, value: unknown) => TerminalQueryBuilder;
  contains: (column: string, value: unknown) => TerminalQueryBuilder;
  or: (expr: string) => TerminalQueryBuilder;
  match: (obj: Record<string, unknown>) => TerminalQueryBuilder;
  order: (column: string, options?: { ascending?: boolean }) => TerminalQueryBuilder;
  range: (from: number, to: number) => TerminalQueryBuilder;
  limit: (n: number) => TerminalQueryBuilder;
  single: () => TerminalQueryBuilder;
  maybeSingle: () => TerminalQueryBuilder;
  then: (resolve: (value: BridgeResult) => unknown, reject?: AnyFn) => Promise<unknown>;
  catch: (reject: AnyFn) => Promise<unknown>;
  finally: (cb: AnyFn) => Promise<unknown>;
}

// Tipo de retorno de supabase.from(table) — todos os métodos disponíveis,
// encadeáveis, sem `as any`.
type ChainableQueryBuilder = TerminalQueryBuilder;

// Tipo exportado de supabase.from(table) — visível externamente via Module augmentation.
export type QueryBuilderType = ChainableQueryBuilder;

const createQueryBuilder = (table: string): TerminalQueryBuilder => {
  const state: { action: Action; payload: BridgePayload } = {
    action: 'select',
    payload: { filters: [] },
  };

  const exec = <T = any>() => callBridge<T>(state.action, table, state.payload);

  const addFilter = (column: string, op: string, value: unknown): TerminalQueryBuilder => {
    // Se o valor for "undefined" ou "null" como string, converte para null real.
    // Se for "all", ignoramos o filtro para permitir listagem completa.
    if (value === "all") return builder;
    
    // Filtros de busca vazios não devem ser aplicados
    if (value === "" && (op === 'ilike' || op === 'like')) return builder;

    const cleanValue = (value === "undefined" || value === "null") ? null : value;
    state.payload.filters = [...(state.payload.filters || []), { column, op, value: cleanValue }];
    return builder;
  };

  const builder: TerminalQueryBuilder = {
    select: (columns = '*', options: { count?: string } = {}) => {
      state.payload.columns = columns;
      if (options.count) {
        state.payload.countMode = options.count;
      }
      return builder;
    },
    insert: (data: Record<string, unknown> | Record<string, unknown>[]) => {
      state.action = 'insert';
      state.payload.data = data;
      return builder;
    },
    update: (data: Record<string, unknown>) => {
      state.action = 'update';
      state.payload.data = data;
      return builder;
    },
    delete: () => {
      state.action = 'delete';
      return builder;
    },
    upsert: (data: Record<string, unknown> | Record<string, unknown>[]) => {
      state.action = 'upsert';
      state.payload.data = data;
      return builder;
    },
    eq: (c: string, v: unknown) => addFilter(c, 'eq', v),
    neq: (c: string, v: unknown) => addFilter(c, 'neq', v),
    gt: (c: string, v: unknown) => addFilter(c, 'gt', v),
    gte: (c: string, v: unknown) => addFilter(c, 'gte', v),
    lt: (c: string, v: unknown) => addFilter(c, 'lt', v),
    lte: (c: string, v: unknown) => addFilter(c, 'lte', v),
    like: (c: string, v: unknown) => addFilter(c, 'like', v),
    ilike: (c: string, v: unknown) => addFilter(c, 'ilike', v),
    in: (c: string, v: unknown[]) => addFilter(c, 'in', v),
    is: (c: string, v: unknown) => addFilter(c, 'is', v),
    not: (c: string, op: string, v: unknown) => {
      const cleanValue = (v === "undefined" || v === "null") ? null : v;
      state.payload.filters = [...(state.payload.filters || []), { column: c, op: 'not', value: cleanValue, extraOp: op }];
      return builder;
    },
    contains: (c: string, v: unknown) => addFilter(c, 'contains', v),
    or: (expr: string) => {
      state.payload.filters = [...(state.payload.filters || []), { column: '', op: 'or', value: expr }];
      return builder;
    },
    match: (obj: Record<string, unknown>) => {
      Object.entries(obj).forEach(([k, v]) => addFilter(k, 'eq', v));
      return builder;
    },
    order: (column: string, options: { ascending?: boolean } = {}) => {
      state.payload.order = { column, ascending: options.ascending !== false };
      return builder;
    },
    range: (from: number, to: number) => {
      state.payload.offset = from;
      state.payload.limit = to - from + 1;
      return builder;
    },
    limit: (n: number) => {
      state.payload.limit = n;
      return builder;
    },
    single: () => { state.payload.single = true; return builder; },
    maybeSingle: () => { state.payload.single = true; return builder; },
    then: (resolve: (value: BridgeResult) => unknown, reject?: AnyFn) => exec().then(resolve, reject),
    catch: (reject: AnyFn) => exec().catch(reject),
    finally: (cb: AnyFn) => exec().finally(cb),
  };

  return builder;
};

 
interface SupabaseProxyTarget {
  from: (table: string) => ChainableQueryBuilder;
  rpc: (fn: string, params: Record<string, unknown>) => Promise<BridgeResponse<any>>;
  [key: string]: unknown;
}

const proxyTarget: SupabaseProxyTarget = {
  from: (table: string) => createQueryBuilder(table),
  rpc: (fn: string, params: Record<string, unknown>) =>
    callBridge('rpc', fn, { params }),
};

const dbBridgeProxy: ProxyHandler<SupabaseProxyTarget> = {
  get(target, prop, receiver) {
    if (prop === 'from') return (table: string) => createQueryBuilder(table);
    if (prop === 'rpc') return (fn: string, params: Record<string, unknown>) =>
      callBridge('rpc', fn, { params });
    return Reflect.get(target, prop, receiver);
  }
};

export const supabase = new Proxy(
  supabaseBase as unknown as SupabaseProxyTarget,
  dbBridgeProxy
) as unknown as typeof supabaseBase & SupabaseProxyTarget;