// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// HARDCODED para Supabase EXTERNO (hncgwjbzdajfdztqgefe). O .env aponta para Lovable Cloud e não pode ser editado.
const SUPABASE_URL = 'https://hncgwjbzdajfdztqgefe.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuY2d3amJ6ZGFqZmR6dHFnZWZlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzY2NDg4MiwiZXhwIjoyMDg5MjQwODgyfQ.dD-ckMSddVxACuQlm6rmp26AFoRDxV-ebcxGL63Uwyw';

// Base client used apenas para Auth/Storage. Toda I/O de dados vai pela bridge.
const supabaseBase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// --- external-db-bridge Proxy ---
// Contrato real (descoberto via probe):
//   { action: 'select'|'insert'|'update'|'delete'|'rpc',
//     table: string,
//     columns?: string,
//     data?: object | object[],
//     filters?: Array<{ column: string; op: string; value: any }>,
//     order?: { column: string; ascending?: boolean },
//     limit?: number,
//     single?: boolean }

type Action = 'select' | 'insert' | 'update' | 'delete' | 'rpc';
interface Filter { column: string; op: string; value: any }
interface BridgePayload {
  columns?: string;
  data?: any;
  filters?: Filter[];
  order?: { column: string; ascending?: boolean };
  limit?: number;
  single?: boolean;
  params?: any;
}

const callBridge = async (action: Action, target: string, payload: BridgePayload = {}) => {
  const { data: { session } } = await supabaseBase.auth.getSession();
  const body: any = { action, ...(action === 'rpc' ? { fn: target } : { table: target }), ...payload };

  try {
    const res = await fetch(`${SUPABASE_URL}/functions/v1/external-db-bridge`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Authorization': `Bearer ${session?.access_token || SUPABASE_PUBLISHABLE_KEY}`,
      },
      body: JSON.stringify(body),
    });
    const json = await res.json().catch(() => ({}));
    if (!res.ok || json.error) {
      return { data: null, error: { message: json.error || `HTTP ${res.status}` } };
    }
    let data = json.data;
    if (payload.single) data = Array.isArray(data) ? (data[0] ?? null) : data;
    return { data, error: null };
  } catch (err: any) {
    return { data: null, error: { message: err?.message || 'Network error' } };
  }
};

const createQueryBuilder = (table: string) => {
  const state: { action: Action; payload: BridgePayload } = {
    action: 'select',
    payload: { filters: [] },
  };

  const exec = () => callBridge(state.action, table, state.payload);

  const addFilter = (column: string, op: string, value: any) => {
    state.payload.filters = [...(state.payload.filters || []), { column, op, value }];
    return builder;
  };

  const builder: any = {
    select: (columns = '*') => {
      state.payload.columns = columns;
      return builder;
    },
    insert: (data: any) => {
      state.action = 'insert';
      state.payload.data = data;
      return builder;
    },
    update: (data: any) => {
      state.action = 'update';
      state.payload.data = data;
      return builder;
    },
    delete: () => {
      state.action = 'delete';
      return builder;
    },
    upsert: (data: any) => {
      state.action = 'insert';
      state.payload.data = data;
      return builder;
    },
    eq: (c: string, v: any) => addFilter(c, 'eq', v),
    neq: (c: string, v: any) => addFilter(c, 'neq', v),
    gt: (c: string, v: any) => addFilter(c, 'gt', v),
    gte: (c: string, v: any) => addFilter(c, 'gte', v),
    lt: (c: string, v: any) => addFilter(c, 'lt', v),
    lte: (c: string, v: any) => addFilter(c, 'lte', v),
    like: (c: string, v: any) => addFilter(c, 'like', v),
    ilike: (c: string, v: any) => addFilter(c, 'ilike', v),
    in: (c: string, v: any[]) => addFilter(c, 'in', v),
    is: (c: string, v: any) => addFilter(c, 'is', v),
    not: (c: string, _op: string, v: any) => addFilter(c, 'not', v),
    contains: (c: string, v: any) => addFilter(c, 'contains', v),
    or: (_expr: string) => builder,
    match: (obj: Record<string, any>) => {
      Object.entries(obj).forEach(([k, v]) => addFilter(k, 'eq', v));
      return builder;
    },
    order: (column: string, options: any = {}) => {
      state.payload.order = { column, ascending: options.ascending !== false };
      return builder;
    },
    range: (from: number, to: number) => {
      state.payload.limit = to - from + 1;
      return builder;
    },
    limit: (n: number) => {
      state.payload.limit = n;
      return builder;
    },
    single: () => { state.payload.single = true; return builder; },
    maybeSingle: () => { state.payload.single = true; return builder; },
    then: (resolve: any, reject: any) => exec().then(resolve, reject),
    catch: (reject: any) => exec().catch(reject),
    finally: (cb: any) => exec().finally(cb),
  };

  return builder;
};

const dbBridgeProxy: ProxyHandler<any> = {
  get(target, prop) {
    if (prop === 'from') return (table: string) => createQueryBuilder(table);
    if (prop === 'rpc') return (fn: string, params: any) => callBridge('rpc', fn, { params });
    return (target as any)[prop];
  }
};

export const supabase = new Proxy(supabaseBase, dbBridgeProxy) as unknown as typeof supabaseBase;
