// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { toast } from 'sonner';
import type { Database } from './types';

// Configurações do Supabase EXTERNO (hncgwjbzdajfdztqgefe) via .env
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("Supabase env variables are missing. Using defaults for hncgwjbzdajfdztqgefe.");
}

// Base client usado para Auth/Storage. Toda I/O de dados vai pela bridge.
const supabaseBase = createClient<Database>(
  SUPABASE_URL || 'https://hncgwjbzdajfdztqgefe.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuY2d3amJ6ZGFqZmR6dHFnZWZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2NjQ4ODIsImV4cCI6MjA4OTI0MDg4Mn0.B9ml1sHPkPHoTEWBapO3z1y1RNVpMQfT9Ws0srULlzE',

  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

// --- external-db-bridge Proxy ---
// Contrato real (descoberto via probe):
//   { action: 'select'|'insert'|'update'|'delete'|'rpc',
//     table: string,
//     columns?: string,
//     data?: object | object[],
//     filters?: Array<{ column: string; op: string; value: any }>,
//     order?: { column: string; ascending?: boolean },
//     limit?: number,
//     single?: boolean }

type Action = 'select' | 'insert' | 'update' | 'delete' | 'rpc';
interface Filter { column: string; op: string; value: any }
interface BridgePayload {
  columns?: string;
  data?: any;
  filters?: Filter[];
  order?: { column: string; ascending?: boolean };
  limit?: number;
  offset?: number;
  single?: boolean;
  countMode?: string;
  params?: any;
}

const callBridge = async (action: Action, target: string, payload: BridgePayload = {}) => {
  const { data: { session } } = await supabaseBase.auth.getSession();
  const body: any = { action, ...(action === 'rpc' ? { fn: target } : { table: target }), ...payload };

  try {
    const res = await fetch(`${SUPABASE_URL}/functions/v1/external-db-bridge`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Authorization': `Bearer ${session?.access_token || SUPABASE_PUBLISHABLE_KEY}`,
      },
      body: JSON.stringify(body),
    });
    const json = await res.json().catch(() => ({}));
    if (!res.ok || json.error) {
      const errorMsg = json.error || `Erro HTTP ${res.status}`;
      console.error('🔴 [BRIDGE_SCHEMA_ERROR]', errorMsg);
      
      // Grita no UI para o desenvolvedor ver exatamente o que falta
      toast.error(`ERRO DE BANCO: ${errorMsg}`, {
        duration: 10000, // 10 segundos para dar tempo de ler
        style: { background: '#fee2e2', color: '#991b1b', border: '1px solid #f87171' },
      });

      throw new Error(errorMsg);
    }
    let data = json.data;
    if (payload.single) data = Array.isArray(data) ? (data[0] ?? null) : data;
    return { data, count: json.count, error: null };
  } catch (err: any) {
    return { data: null, error: { message: err?.message || 'Network error' } };
  }
};

const createQueryBuilder = (table: string) => {
  const state: { action: Action; payload: BridgePayload } = {
    action: 'select',
    payload: { filters: [] },
  };

  const exec = () => callBridge(state.action, table, state.payload);

  const addFilter = (column: string, op: string, value: any) => {
    // Se o valor for "undefined" ou "null" como string (comum em erros de template string), 
    // converte para null real. Se for undefined real, JSON.stringify o removerá.
    const cleanValue = (value === "undefined" || value === "null") ? null : value;
    state.payload.filters = [...(state.payload.filters || []), { column, op, value: cleanValue }];
    return builder;
  };

  const builder: any = {
    select: (columns = '*', options: any = {}) => {
      state.payload.columns = columns;
      if (options.count) {
        state.payload.countMode = options.count;
      }
      return builder;
    },
    insert: (data: any) => {
      state.action = 'insert';
      state.payload.data = data;
      return builder;
    },
    update: (data: any) => {
      state.action = 'update';
      state.payload.data = data;
      return builder;
    },
    delete: () => {
      state.action = 'delete';
      return builder;
    },
    upsert: (data: any) => {
      state.action = 'insert';
      state.payload.data = data;
      return builder;
    },
    eq: (c: string, v: any) => addFilter(c, 'eq', v),
    neq: (c: string, v: any) => addFilter(c, 'neq', v),
    gt: (c: string, v: any) => addFilter(c, 'gt', v),
    gte: (c: string, v: any) => addFilter(c, 'gte', v),
    lt: (c: string, v: any) => addFilter(c, 'lt', v),
    lte: (c: string, v: any) => addFilter(c, 'lte', v),
    like: (c: string, v: any) => addFilter(c, 'like', v),
    ilike: (c: string, v: any) => addFilter(c, 'ilike', v),
    in: (c: string, v: any[]) => addFilter(c, 'in', v),
    is: (c: string, v: any) => addFilter(c, 'is', v),
    not: (c: string, _op: string, v: any) => addFilter(c, 'not', v),
    contains: (c: string, v: any) => addFilter(c, 'contains', v),
    or: (_expr: string) => builder,
    match: (obj: Record<string, any>) => {
      Object.entries(obj).forEach(([k, v]) => addFilter(k, 'eq', v));
      return builder;
    },
    order: (column: string, options: any = {}) => {
      state.payload.order = { column, ascending: options.ascending !== false };
      return builder;
    },
    range: (from: number, to: number) => {
      state.payload.limit = to - from + 1;
      return builder;
    },
    limit: (n: number) => {
      state.payload.limit = n;
      return builder;
    },
    single: () => { state.payload.single = true; return builder; },
    maybeSingle: () => { state.payload.single = true; return builder; },
    then: (resolve: any, reject: any) => exec().then(resolve, reject),
    catch: (reject: any) => exec().catch(reject),
    finally: (cb: any) => exec().finally(cb),
  };

  return builder;
};

const dbBridgeProxy: ProxyHandler<any> = {
  get(target, prop) {
    if (prop === 'from') return (table: string) => createQueryBuilder(table);
    if (prop === 'rpc') return (fn: string, params: any) => callBridge('rpc', fn, { params });
    return (target as any)[prop];
  }
};

export const supabase = new Proxy(supabaseBase, dbBridgeProxy) as unknown as typeof supabaseBase;
