name: Deploy Oficial Supabase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy All Functions
        run: |
          for dir in supabase/functions/*/; do
            name=$(basename "$dir")
            if [ "$name" != "_shared" ]; then
              echo "Deploying $name..."
              supabase functions deploy "$name" --project-ref hncgwjbzdajfdztqgefe --no-verify-jwt
            fi
          done
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
