import type { Meta, StoryObj } from '@storybook/react';
import { Alert, AlertTitle, AlertDescription } from './alert';
import { AlertTriangle, CheckCircle, Info, XCircle } from 'lucide-react';
const meta: Meta<typeof Alert> = { title: 'UI/Alert', component: Alert, tags: ['autodocs'] };
export default meta;
type Story = StoryObj<typeof Alert>;
export const Default: Story = { render: () => <Alert><AlertTitle>Atenção</AlertTitle><AlertDescription>Esta é uma mensagem de alerta padrão.</AlertDescription></Alert> };
export const Success: Story = { render: () => <Alert className="border-green-500 bg-green-50"><CheckCircle className="h-4 w-4 text-green-600" /><AlertTitle className="text-green-800">Sucesso!</AlertTitle><AlertDescription className="text-green-700">Operação realizada com sucesso.</AlertDescription></Alert> };
export const Warning: Story = { render: () => <Alert className="border-yellow-500 bg-yellow-50"><AlertTriangle className="h-4 w-4 text-yellow-600" /><AlertTitle className="text-yellow-800">Atenção</AlertTitle><AlertDescription className="text-yellow-700">Verifique os dados antes de continuar.</AlertDescription></Alert> };
export const Error: Story = { render: () => <Alert variant="destructive"><XCircle className="h-4 w-4" /><AlertTitle>Erro</AlertTitle><AlertDescription>Ocorreu um erro ao processar a solicitação.</AlertDescription></Alert> };
