import type { Meta, StoryObj } from '@storybook/react';
import { Badge } from './badge';
const meta: Meta<typeof Badge> = { title: 'UI/Badge', component: Badge, tags: ['autodocs'] };
export default meta;
type Story = StoryObj<typeof Badge>;
export const Default: Story = { args: { children: 'Badge' } };
export const Secondary: Story = { args: { children: 'Secondary', variant: 'secondary' } };
export const Destructive: Story = { args: { children: 'Destructive', variant: 'destructive' } };
export const Outline: Story = { args: { children: 'Outline', variant: 'outline' } };
export const Status: Story = { render: () => <div className="flex gap-2"><Badge className="bg-green-100 text-green-800">Ativo</Badge><Badge className="bg-red-100 text-red-800">Inativo</Badge><Badge className="bg-yellow-100 text-yellow-800">Pendente</Badge></div> };
