import type { Meta, StoryObj } from '@storybook/react';
import { Checkbox } from './checkbox';
import { Label } from './label';
const meta: Meta<typeof Checkbox> = { title: 'UI/Checkbox', component: Checkbox, tags: ['autodocs'] };
export default meta;
type Story = StoryObj<typeof Checkbox>;
export const Default: Story = { args: {} };
export const Checked: Story = { args: { defaultChecked: true } };
export const WithLabel: Story = { render: () => <div className="flex items-center gap-2"><Checkbox id="terms" /><Label htmlFor="terms">Aceito os termos</Label></div> };
export const Disabled: Story = { args: { disabled: true } };
