import type { Meta, StoryObj } from '@storybook/react';
import { Switch } from './switch';
import { Label } from './label';
const meta: Meta<typeof Switch> = { title: 'UI/Switch', component: Switch, tags: ['autodocs'] };
export default meta;
type Story = StoryObj<typeof Switch>;
export const Default: Story = { args: {} };
export const Checked: Story = { args: { defaultChecked: true } };
export const WithLabel: Story = { render: () => <div className="flex items-center gap-2"><Switch id="airplane" /><Label htmlFor="airplane">Ativo</Label></div> };
export const Disabled: Story = { args: { disabled: true } };
